name: flutter_cms_generator
description: "Code generators for Flutter CMS"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_cms_annotation:
    path: ../flutter_cms_annotation
  source_gen: ^4.1.1
  build: ^4.0.3
  code_builder: ^4.10.0
  analyzer: ^9.0.0
  dart_style: ^3.1.3
  pub_semver: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^3.5.4
  test: ^1.24.0
