name: example_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  example_app: 
    path: ../example_app
  flutter_cms:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
