name: flutter_cms
description: "CMS studio interface with inputs, validators, and runtime components for Flutter CMS applications"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_cms_annotation:
    path: ../flutter_cms_annotation
  flutter:
    sdk: flutter
  shadcn_ui: ^0.39.14
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.0
  solidart: ^2.8.2
  flutter_solidart: ^2.7.1
  flutter_resizable_container: ^4.2.0
  super_editor: ^0.3.0-dev.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
